###
# Register a new user
# @desc: Register a new user
# @route: POST /api/users
# @access: Public
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "name": "John Doe4",
  "email": "johndoe4@example.com",
  "password": "password123"
}

###
# Authenticate user
# @desc: Authenticate user
# @route: POST /api/users/auth
# @access: Public
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "name": "John Doe4",
  "email": "johndoe4@example.com",
  "password": "password123"
}

###
# Logout User
# @desc: Logout user
# @route: POST /api/users/logout
# @access: Private
POST http://localhost:8080/api/users/logout
Content-Type: application/json
Cookie: token=YOUR_TOKEN_HERE

###
# Get User Profile
# @desc: Get user profile
# @route: GET /api/users/profile
# @access: Private
GET http://localhost:8080/api/users/profile
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTY4NDczMzgxOSwiZXhwIjoxNjg3MzI1ODE5fQ.afqWA0bGvAAvZTIx0z9pgk5SvAjUsSMFswn4vOW95gw

###
# Update User Profile
# @desc: Update user profile
# @route: PUT /api/users/profile
# @access: Private
PUT http://localhost:8080/api/users/profile
Content-Type: application/json
Cookie: token=YOUR_TOKEN_HERE

{
  "name": "Jane Doe",
  "email": "janedoe@example.com",
  "password": "password456"
}
