@new_user_name =John Doe
@new_user_email =johndoe@example.com
@new_user_password =password123

@update_user_name =Update John Doe
@update_user_email =update_johndoe@example.com
@update_user_password =password123

@token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTY4NDczMzgxOSwiZXhwIjoxNjg3MzI1ODE9fQ.afqWA0bGvAAvZTIx0z9pgk5SvAjUsSMFswn4vOW95gw"

###
# Register a new user
# @desc: Register a new user
# @route: POST /api/users
# @access: Public
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "name": "{{new_user_name}}",
  "email": "{{new_user_email}}",
  "password": "{{new_user_password}}"
}

###
# Authenticate user
# @desc: Authenticate user
# @route: POST /api/users/auth
# @access: Public
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "{{new_user_email}}",
  "password": "{{new_user_password}}"
}

###
# Logout User
# @desc: Logout user
# @route: POST /api/users/logout
# @access: Private
POST http://localhost:8080/api/users/logout
Content-Type: application/json

###
# Get User Profile
# @desc: Get user profile
# @route: GET /api/users/profile
# @access: Private
GET http://localhost:8080/api/users/profile
Content-Type: application/json

###
# Update User Profile
# @desc: Update user profile
# @route: PUT /api/users/profile
# @access: Private
PUT http://localhost:8080/api/users/profile
Content-Type: application/json

{
  "name": "{{update_user_name}}",
  "email": "{{update_user_email}}",
  "password": "{{update_user_password}}"
}

